// // largely generated by ChatGPT

#include <algorithm> // For std::min, std::max
#include <set>       // For ensuring unique candidate triangles
#include "elliptic.hpp" // User's include, kept for their environment
#include <omp.h>

#define HEXNVERTS 8
#define TETNVERTS 4 // Added for tetrahedra
#define TRINVERTS 3

// Max vertices a polygon can have after all clips.
// Triangle vs Hex (3+6=9), Triangle vs Tet (3+4=7). User set to 20, which is safe.
#define MAX_POLY_VERTS 20
// Max triangles from triangulating one polygon with MAX_POLY_VERTS (centroid method)
#define MAX_TRIANGLES_FROM_ONE_CLIP MAX_POLY_VERTS
#define EPSILON 1e-8 // Epsilon for floating point comparisons
#define COINCIDENT_TOLERANCE_SQ (EPSILON * EPSILON) // Squared tolerance for point coincidence


// --- Structures ---
typedef struct {
  dfloat x, y, z;
} Point3D;

typedef struct {
  Point3D v[3];
} Triangle3D;

typedef struct {
  Point3D normal; // Should be unit length
  dfloat d;       // Plane equation: normal.x*x + normal.y*y + normal.z*z + d = 0
} Plane;

// --- AABB Structure ---
typedef struct {
  Point3D min_pt;
  Point3D max_pt;
} AABB;

// --- Vector Operations ---
Point3D vec_sub(Point3D a, Point3D b) { return (Point3D){a.x - b.x, a.y - b.y, a.z - b.z}; }
Point3D vec_add(Point3D a, Point3D b) { return (Point3D){a.x + b.x, a.y + b.y, a.z + b.z}; }
Point3D vec_scale(Point3D v, dfloat s) { return (Point3D){v.x * s, v.y * s, v.z * s}; }
dfloat vec_dot(Point3D a, Point3D b) { return a.x * b.x + a.y * b.y + a.z * b.z; }
Point3D vec_cross(Point3D a, Point3D b) {
  return (Point3D){a.y * b.z - a.z * b.y, a.z * b.x - a.x * b.z, a.x * b.y - a.y * b.x};
}
dfloat vec_length_sq(Point3D v) { return vec_dot(v,v); }
Point3D vec_normalize(Point3D v) {
  dfloat mag_sq = vec_length_sq(v);
  if (mag_sq < EPSILON * EPSILON) return (Point3D){0,0,0}; // Avoid division by zero / NaN
  return vec_scale(v, 1.0 / sqrt(mag_sq));
}

// Helper to check for coincident points
int points_are_coincident(Point3D p1, Point3D p2) {
  Point3D diff = vec_sub(p1, p2);
  return vec_length_sq(diff) < COINCIDENT_TOLERANCE_SQ;
}


// --- Plane Operations ---
Plane create_plane_from_points(Point3D p0, Point3D p1, Point3D p2) {
  Point3D v1 = vec_sub(p1, p0);
  Point3D v2 = vec_sub(p2, p0);
  Point3D normal = vec_normalize(vec_cross(v1, v2));
  dfloat d = -vec_dot(normal, p0);
  return (Plane){normal, d};
}

dfloat point_plane_distance_signed(Point3D p, Plane plane) {
  return vec_dot(plane.normal, p) + plane.d;
}

Point3D project_point_to_plane(Point3D p, Plane plane) {
  if (vec_length_sq(plane.normal) < EPSILON * EPSILON) return p;
  dfloat dist = point_plane_distance_signed(p, plane);
  return vec_sub(p, vec_scale(plane.normal, dist));
}

// --- Intersection (with projection) ---
int segment_plane_intersection(Point3D p1, Point3D p2, Plane clipper_plane,
                               Point3D* intersection_point, Plane original_tri_plane) {
  Point3D line_dir = vec_sub(p2, p1);
  dfloat dot_normal_dir = vec_dot(clipper_plane.normal, line_dir);
  if (fabs(dot_normal_dir) < EPSILON) return 0;
  dfloat t = -(vec_dot(clipper_plane.normal, p1) + clipper_plane.d) / dot_normal_dir;
  if (t < -EPSILON || t > 1.0 + EPSILON) return 0;
  if (t < 0.0) t = 0.0; if (t > 1.0) t = 1.0;
  Point3D raw_intersection = vec_add(p1, vec_scale(line_dir, t));
  *intersection_point = project_point_to_plane(raw_intersection, original_tri_plane);
  return 1;
}

// --- Polygon Clipping (Sutherland-Hodgman edge processing) ---
int clip_polygon_against_plane(Point3D* polygon_in_verts, int n_in, Plane clipper_plane,
                               Point3D* polygon_out_verts, Plane original_tri_plane) {
  if (n_in == 0) return 0;
  int n_out = 0; Point3D S = polygon_in_verts[n_in - 1];
  for (int i = 0; i < n_in; i++) {
    Point3D E = polygon_in_verts[i];
    dfloat dist_S = point_plane_distance_signed(S, clipper_plane);
    dfloat dist_E = point_plane_distance_signed(E, clipper_plane);
    Point3D current_intersection_point;
    if (dist_S <= EPSILON && dist_E <= EPSILON) { // S in, E in
      if (n_out == 0 || !points_are_coincident(E, polygon_out_verts[n_out - 1])) {
	if (n_out < MAX_POLY_VERTS) polygon_out_verts[n_out++] = E; else return MAX_POLY_VERTS;
      }
    } else if (dist_S <= EPSILON && dist_E > EPSILON) { // S in, E out
      if (segment_plane_intersection(S, E, clipper_plane, &current_intersection_point, original_tri_plane)) {
	if (n_out == 0 || !points_are_coincident(current_intersection_point, polygon_out_verts[n_out - 1])) {
	  if (n_out < MAX_POLY_VERTS) polygon_out_verts[n_out++] = current_intersection_point; else return MAX_POLY_VERTS;
	}
      }
    } else if (dist_S > EPSILON && dist_E <= EPSILON) { // S out, E in
      if (segment_plane_intersection(S, E, clipper_plane, &current_intersection_point, original_tri_plane)) {
	if (n_out == 0 || !points_are_coincident(current_intersection_point, polygon_out_verts[n_out - 1])) {
	  if (n_out < MAX_POLY_VERTS) polygon_out_verts[n_out++] = current_intersection_point; else return MAX_POLY_VERTS;
	}
      }
      if (n_out == 0 || !points_are_coincident(E, polygon_out_verts[n_out - 1])) {
	if (n_out < MAX_POLY_VERTS) polygon_out_verts[n_out++] = E; else return MAX_POLY_VERTS;
      }
    } S = E;
  }
  if (n_out > 1 && points_are_coincident(polygon_out_verts[0], polygon_out_verts[n_out - 1])) n_out--;
  return n_out;
}

// --- Centroid Calculation (with projection context) ---
Point3D calculate_polygon_centroid(Point3D* polygon_verts, int n_verts, Plane original_tri_plane) {
  Point3D centroid_raw = {0.0, 0.0, 0.0}; if (n_verts <= 0) return project_point_to_plane(centroid_raw, original_tri_plane);
  for (int i = 0; i < n_verts; i++) {
    centroid_raw.x += polygon_verts[i].x; centroid_raw.y += polygon_verts[i].y; centroid_raw.z += polygon_verts[i].z;
  }
  centroid_raw.x /= (dfloat)n_verts; centroid_raw.y /= (dfloat)n_verts; centroid_raw.z /= (dfloat)n_verts;
  return project_point_to_plane(centroid_raw, original_tri_plane);
}

// --- Triangulation (with projection context) ---
int triangulate_convex_polygon(Point3D* polygon_verts, int n_verts, Triangle3D* triangles,
                               int max_triangles_alloc, Plane original_tri_plane) {
  int n_tri_generated = 0; if (n_verts < 3) return 0;
  if (n_verts == 3) {
    if (!points_are_coincident(polygon_verts[0], polygon_verts[1]) &&
	!points_are_coincident(polygon_verts[1], polygon_verts[2]) &&
	!points_are_coincident(polygon_verts[2], polygon_verts[0])) {
      Point3D edge1 = vec_sub(polygon_verts[1], polygon_verts[0]); Point3D edge2 = vec_sub(polygon_verts[2], polygon_verts[0]);
      if (vec_length_sq(vec_cross(edge1, edge2)) > COINCIDENT_TOLERANCE_SQ * COINCIDENT_TOLERANCE_SQ) { // Check area > 0
	if (n_tri_generated < max_triangles_alloc) {
	  triangles[n_tri_generated].v[0] = polygon_verts[0]; triangles[n_tri_generated].v[1] = polygon_verts[1]; triangles[n_tri_generated].v[2] = polygon_verts[2];
	  n_tri_generated++;
	}
      }
    } return n_tri_generated;
  }
  Point3D centroid = calculate_polygon_centroid(polygon_verts, n_verts, original_tri_plane);
  for (int i = 0; i < n_verts; i++) {
    Point3D p1 = polygon_verts[i]; Point3D p2 = polygon_verts[(i + 1) % n_verts];
    if (!points_are_coincident(p1, p2) && !points_are_coincident(centroid, p1) && !points_are_coincident(centroid, p2) ) {
      Point3D edge_c_p1 = vec_sub(p1, centroid); Point3D edge_c_p2 = vec_sub(p2, centroid);
      if (vec_length_sq(vec_cross(edge_c_p1, edge_c_p2)) > COINCIDENT_TOLERANCE_SQ * COINCIDENT_TOLERANCE_SQ) { // Check area > 0
	if (n_tri_generated < max_triangles_alloc) {
	  triangles[n_tri_generated].v[0] = centroid; triangles[n_tri_generated].v[1] = p1; triangles[n_tri_generated].v[2] = p2;
	  n_tri_generated++;
	} else break;
      }
    }
  } return n_tri_generated;
}

// --- Core Clipping Pipeline (Sutherland-Hodgman with final polygon cleaning) ---
int core_clip_single_polygon_pipeline( Point3D initial_polygon_verts[3], Plane* clipping_planes_list, int n_planes,
				       Triangle3D* output_triangles_list, int max_output_triangles_alloc, Plane original_tri_plane) {
  Point3D polygon_buffer_A[MAX_POLY_VERTS]; Point3D polygon_buffer_B[MAX_POLY_VERTS]; int n_current_verts;
  for (int i = 0; i < 3; i++) polygon_buffer_A[i] = initial_polygon_verts[i];
  n_current_verts = 3;
  Point3D *verts_in_ptr = polygon_buffer_A; Point3D *verts_out_ptr = polygon_buffer_B;
  for (int p_idx = 0; p_idx < n_planes; p_idx++) {
    if (n_current_verts < 3) { n_current_verts = 0; break; }
    Plane current_clipper_plane = clipping_planes_list[p_idx];
    n_current_verts = clip_polygon_against_plane(verts_in_ptr, n_current_verts, current_clipper_plane, verts_out_ptr, original_tri_plane);
    Point3D *temp_ptr = verts_in_ptr; verts_in_ptr = verts_out_ptr; verts_out_ptr = temp_ptr;
  }
  if (n_current_verts < 3) return 0;
  Point3D cleaned_projected_verts[MAX_POLY_VERTS]; int n_cleaned_verts = 0;
  if (n_current_verts > 0) {
    cleaned_projected_verts[0] = project_point_to_plane(verts_in_ptr[0], original_tri_plane);
    n_cleaned_verts = 1;
    for (int i = 1; i < n_current_verts; i++) {
      Point3D projected_v = project_point_to_plane(verts_in_ptr[i], original_tri_plane);
      if (!points_are_coincident(projected_v, cleaned_projected_verts[n_cleaned_verts - 1])) {
	if (n_cleaned_verts < MAX_POLY_VERTS) cleaned_projected_verts[n_cleaned_verts++] = projected_v;
	else break;
      }
    }
    if (n_cleaned_verts > 1 && points_are_coincident(cleaned_projected_verts[n_cleaned_verts - 1], cleaned_projected_verts[0])) {
      n_cleaned_verts--;
    }
  }
  if (n_cleaned_verts < 3) return 0;
  return triangulate_convex_polygon(cleaned_projected_verts, n_cleaned_verts, output_triangles_list, max_output_triangles_alloc, original_tri_plane);
}

// --- Top-Level Clipping Function for Hexahedron ---
int clip_triangle_to_hexahedron( Point3D S_vertices[3], Point3D H_vertices[HEXNVERTS],
				 Triangle3D* output_clipped_triangles, int max_output_tri_count) {
  Plane original_tri_plane = create_plane_from_points(S_vertices[0], S_vertices[1], S_vertices[2]);
  if (vec_length_sq(original_tri_plane.normal) < COINCIDENT_TOLERANCE_SQ) return 0;
  Plane hexahedron_planes[6];
  hexahedron_planes[0] = create_plane_from_points(H_vertices[0], H_vertices[3], H_vertices[2]);
  hexahedron_planes[1] = create_plane_from_points(H_vertices[4], H_vertices[5], H_vertices[6]);
  hexahedron_planes[2] = create_plane_from_points(H_vertices[0], H_vertices[4], H_vertices[7]);
  hexahedron_planes[3] = create_plane_from_points(H_vertices[1], H_vertices[2], H_vertices[6]);
  hexahedron_planes[4] = create_plane_from_points(H_vertices[0], H_vertices[1], H_vertices[5]);
  hexahedron_planes[5] = create_plane_from_points(H_vertices[3], H_vertices[7], H_vertices[6]);
  for(int i=0; i<6; ++i) if (vec_length_sq(hexahedron_planes[i].normal) < COINCIDENT_TOLERANCE_SQ) return 0;
  return core_clip_single_polygon_pipeline( S_vertices, hexahedron_planes, 6, output_clipped_triangles, max_output_tri_count, original_tri_plane );
}

// --- Helper to create Tetrahedron Planes with Outward Normals ---
void create_tetrahedron_planes_outward(Point3D T_vertices[TETNVERTS], Plane tet_planes[4]) {
  Point3D V[4] = {T_vertices[0], T_vertices[1], T_vertices[2], T_vertices[3]};
  Plane p_test;

  // Face 0: V0,V1,V2 (opposite V3)
  p_test = create_plane_from_points(V[0], V[1], V[2]);
  if (point_plane_distance_signed(V[3], p_test) > -COINCIDENT_TOLERANCE_SQ) // V3 on "positive" (normal) side or on plane -> normal is inward
    tet_planes[0] = create_plane_from_points(V[0], V[2], V[1]); // Flipped winding for outward normal
  else tet_planes[0] = p_test;

  // Face 1: V0,V3,V1 (opposite V2) -> (V0,V1,V3) for CCW if V2 is "behind"
  p_test = create_plane_from_points(V[0], V[1], V[3]); // V0,V1,V3
  if (point_plane_distance_signed(V[2], p_test) > -COINCIDENT_TOLERANCE_SQ)
    tet_planes[1] = create_plane_from_points(V[0], V[3], V[1]); // V0,V3,V1
  else tet_planes[1] = p_test;

  // Face 2: V0,V2,V3 (opposite V1) -> (V0,V3,V2) for CCW if V1 is "behind"
  p_test = create_plane_from_points(V[0], V[3], V[2]); // V0,V3,V2
  if (point_plane_distance_signed(V[1], p_test) > -COINCIDENT_TOLERANCE_SQ)
    tet_planes[2] = create_plane_from_points(V[0], V[2], V[3]); // V0,V2,V3
  else tet_planes[2] = p_test;
        
  // Face 3: V1,V2,V3 (opposite V0)
  p_test = create_plane_from_points(V[1], V[2], V[3]);
  if (point_plane_distance_signed(V[0], p_test) > -COINCIDENT_TOLERANCE_SQ)
    tet_planes[3] = create_plane_from_points(V[1], V[3], V[2]);
  else tet_planes[3] = p_test;
}


// --- Top-Level Clipping Function for Tetrahedron ---
int clip_triangle_to_tetrahedron( Point3D S_vertices[3], Point3D T_vertices[TETNVERTS],
				  Triangle3D* output_clipped_triangles, int max_output_tri_count) {
  Plane original_tri_plane = create_plane_from_points(S_vertices[0], S_vertices[1], S_vertices[2]);
  if (vec_length_sq(original_tri_plane.normal) < COINCIDENT_TOLERANCE_SQ) return 0;
    
  Plane tetrahedron_planes[4];
  create_tetrahedron_planes_outward(T_vertices, tetrahedron_planes);

  for(int i=0; i<4; ++i) if (vec_length_sq(tetrahedron_planes[i].normal) < COINCIDENT_TOLERANCE_SQ) return 0; // Check all tet planes

  return core_clip_single_polygon_pipeline( S_vertices, tetrahedron_planes, 4, output_clipped_triangles, max_output_tri_count, original_tri_plane);
}





// --- AABB Utility Functions ---
AABB create_aabb_triangle(const Point3D tri_verts[TRINVERTS]) {
  AABB box;
  box.min_pt = tri_verts[0];
  box.max_pt = tri_verts[0];
  for (int i = 1; i < TRINVERTS; ++i) {
    box.min_pt.x = std::min(box.min_pt.x, tri_verts[i].x);
    box.min_pt.y = std::min(box.min_pt.y, tri_verts[i].y);
    box.min_pt.z = std::min(box.min_pt.z, tri_verts[i].z);
    box.max_pt.x = std::max(box.max_pt.x, tri_verts[i].x);
    box.max_pt.y = std::max(box.max_pt.y, tri_verts[i].y);
    box.max_pt.z = std::max(box.max_pt.z, tri_verts[i].z);
  }
  return box;
}

AABB create_aabb_polyhedron(const Point3D* poly_verts, int num_poly_verts) {
  AABB box;
  if (num_poly_verts == 0) {
    box.min_pt = box.max_pt = {0,0,0};
    return box;
  }
  box.min_pt = poly_verts[0];
  box.max_pt = poly_verts[0];
  for (int i = 1; i < num_poly_verts; ++i) {
    box.min_pt.x = std::min(box.min_pt.x, poly_verts[i].x);
    box.min_pt.y = std::min(box.min_pt.y, poly_verts[i].y);
    box.min_pt.z = std::min(box.min_pt.z, poly_verts[i].z);
    box.max_pt.x = std::max(box.max_pt.x, poly_verts[i].x);
    box.max_pt.y = std::max(box.max_pt.y, poly_verts[i].y);
    box.max_pt.z = std::max(box.max_pt.z, poly_verts[i].z);
  }
  return box;
}

int aabbs_intersect(const AABB& a, const AABB& b) {
  if (a.max_pt.x < b.min_pt.x - EPSILON || a.min_pt.x > b.max_pt.x + EPSILON) return 0;
  if (a.max_pt.y < b.min_pt.y - EPSILON || a.min_pt.y > b.max_pt.y + EPSILON) return 0;
  if (a.max_pt.z < b.min_pt.z - EPSILON || a.min_pt.z > b.max_pt.z + EPSILON) return 0;
  return 1;
}


// --- Spatial Grid Structure ---
typedef struct {
  Point3D domain_min;
  Point3D domain_max;
  Point3D cell_size;
  int dims[3]; // Number of cells in x, y, z
  std::vector<std::vector<dlong>> cells_data; // Flattened cell data
  std::vector<AABB> triangle_aabbs_cache; // Cache AABBs of surface triangles

  // Initializes the grid based on overall domain and desired number of cells per dimension
  void init(const Point3D& min_coord, const Point3D& max_coord, int approx_cells_per_dim = 32) {
    domain_min = min_coord;
    domain_max = max_coord;

    Point3D extent = vec_sub(domain_max, domain_min);

    if (extent.x < EPSILON) extent.x = EPSILON; // Avoid division by zero if dimension is flat
    if (extent.y < EPSILON) extent.y = EPSILON;
    if (extent.z < EPSILON) extent.z = EPSILON;
        
    dims[0] = std::max(1, (int)ceil(extent.x / (extent.x / std::max(1, approx_cells_per_dim))));
    dims[1] = std::max(1, (int)ceil(extent.y / (extent.y / std::max(1, approx_cells_per_dim))));
    dims[2] = std::max(1, (int)ceil(extent.z / (extent.z / std::max(1, approx_cells_per_dim))));
        
    // Ensure dimensions are at least 1
    for(int i=0; i<3; ++i) if(dims[i] == 0) dims[i] = 1;


    cell_size.x = extent.x / dims[0];
    cell_size.y = extent.y / dims[1];
    cell_size.z = extent.z / dims[2];

    // Ensure cell_size is not zero if extent was initially zero for a dimension
    if (cell_size.x < EPSILON) cell_size.x = EPSILON;
    if (cell_size.y < EPSILON) cell_size.y = EPSILON;
    if (cell_size.z < EPSILON) cell_size.z = EPSILON;

    cells_data.assign(dims[0] * dims[1] * dims[2], std::vector<dlong>());
    // printf("Grid initialized: Min(%.2f,%.2f,%.2f) Max(%.2f,%.2f,%.2f)\n", domain_min.x, domain_min.y, domain_min.z, domain_max.x, domain_max.y, domain_max.z);
    // printf("Grid Dims: %d x %d x %d, CellSize: (%.3f, %.3f, %.3f)\n", dims[0],dims[1],dims[2], cell_size.x, cell_size.y, cell_size.z);
  }
    
  void cache_triangle_aabbs(const memory<dfloat>& sEX, const memory<dfloat>& sEY, const memory<dfloat>& sEZ, dlong Nsurf) {
    triangle_aabbs_cache.resize(Nsurf);
    for (dlong s = 0; s < Nsurf; ++s) {
      Point3D tri_v[TRINVERTS] = {
	{sEX[s*TRINVERTS+0], sEY[s*TRINVERTS+0], sEZ[s*TRINVERTS+0]},
	{sEX[s*TRINVERTS+1], sEY[s*TRINVERTS+1], sEZ[s*TRINVERTS+1]},
	{sEX[s*TRINVERTS+2], sEY[s*TRINVERTS+2], sEZ[s*TRINVERTS+2]}
      };
      triangle_aabbs_cache[s] = create_aabb_triangle(tri_v);
    }
  }


  void insert_triangle(dlong triangle_idx) { // Assumes AABB is in triangle_aabbs_cache
    if (triangle_idx >= triangle_aabbs_cache.size()) return;
    const AABB& tri_aabb = triangle_aabbs_cache[triangle_idx];

    int min_ix = std::max(0, (int)floor((tri_aabb.min_pt.x - domain_min.x) / cell_size.x));
    int max_ix = std::min(dims[0] - 1, (int)floor((tri_aabb.max_pt.x - domain_min.x) / cell_size.x));
    int min_iy = std::max(0, (int)floor((tri_aabb.min_pt.y - domain_min.y) / cell_size.y));
    int max_iy = std::min(dims[1] - 1, (int)floor((tri_aabb.max_pt.y - domain_min.y) / cell_size.y));
    int min_iz = std::max(0, (int)floor((tri_aabb.min_pt.z - domain_min.z) / cell_size.z));
    int max_iz = std::min(dims[2] - 1, (int)floor((tri_aabb.max_pt.z - domain_min.z) / cell_size.z));

    for (int iz = min_iz; iz <= max_iz; ++iz) {
      for (int iy = min_iy; iy <= max_iy; ++iy) {
	for (int ix = min_ix; ix <= max_ix; ++ix) {
	  dlong cell_flat_idx = (dlong)ix + (dlong)iy * dims[0] + (dlong)iz * dims[0] * dims[1];
	  if (cell_flat_idx < cells_data.size()) {
	    cells_data[cell_flat_idx].push_back(triangle_idx);
	  }
	}
      }
    }
  }

  void get_candidate_triangles(const AABB& query_aabb, std::set<dlong>& unique_candidates) const {

    unique_candidates.clear();

    int min_ix = std::max(0, (int)floor((query_aabb.min_pt.x - domain_min.x) / cell_size.x));
    int max_ix = std::min(dims[0] - 1, (int)floor((query_aabb.max_pt.x - domain_min.x) / cell_size.x));
    int min_iy = std::max(0, (int)floor((query_aabb.min_pt.y - domain_min.y) / cell_size.y));
    int max_iy = std::min(dims[1] - 1, (int)floor((query_aabb.max_pt.y - domain_min.y) / cell_size.y));
    int min_iz = std::max(0, (int)floor((query_aabb.min_pt.z - domain_min.z) / cell_size.z));
    int max_iz = std::min(dims[2] - 1, (int)floor((query_aabb.max_pt.z - domain_min.z) / cell_size.z));

    for (int iz = min_iz; iz <= max_iz; ++iz) {
      for (int iy = min_iy; iy <= max_iy; ++iy) {
	for (int ix = min_ix; ix <= max_ix; ++ix) {
	  dlong cell_flat_idx = (dlong)ix + (dlong)iy * dims[0] + (dlong)iz * dims[0] * dims[1];
	  if (cell_flat_idx < cells_data.size()) {
	    for (dlong tri_idx : cells_data[cell_flat_idx]) {
	      unique_candidates.insert(tri_idx);
	    }
	  }
	}
      }
    }
  }
} SpatialGrid;



// --- Renamed Hexahedron Intersection Function ---
void computeIntersectionsHex3D(
			       const memory<dfloat> &EX, const memory<dfloat> &EY, const memory<dfloat> &EZ,
			       const memory<dfloat> &sEX, const memory<dfloat> &sEY, const memory<dfloat> &sEZ,
			       std::vector<std::vector<dfloat>> &fEX, std::vector<std::vector<dfloat>> &fEY,
			       std::vector<std::vector<dfloat>> &fEZ, dlong Nel, dlong Nsurf){

  dfloat xmin = sEX[0], ymin = sEY[0], zmin = sEZ[0];
  dfloat xmax = sEX[0], ymax = sEY[0], zmax = sEZ[0];

  for (dlong e = 0; e < Nsurf; ++e) {
    for (int i = 0; i < TRINVERTS; ++i) {
      xmin = std::min(xmin, sEX[e*TRINVERTS+i]);
      xmax = std::max(xmax, sEX[e*TRINVERTS+i]);
      ymin = std::min(ymin, sEY[e*TRINVERTS+i]);
      ymax = std::max(ymax, sEY[e*TRINVERTS+i]);
      zmin = std::min(zmin, sEZ[e*TRINVERTS+i]);
      zmax = std::max(zmax, sEZ[e*TRINVERTS+i]);
    }
  }

  SpatialGrid surface_grid;
  Point3D domain_min, domain_max;
  
  domain_min = {xmin, ymin, zmin};
  domain_max = {xmax, ymax, zmax};
  surface_grid.init(domain_min, domain_max, 32);
  surface_grid.cache_triangle_aabbs(sEX, sEY, sEZ, Nsurf);
  for (dlong s = 0; s < Nsurf; ++s) surface_grid.insert_triangle(s);
  
  fEX.assign(Nel, {}); fEY.assign(Nel, {}); fEZ.assign(Nel, {});
  Triangle3D clipped_tris_buffer[MAX_TRIANGLES_FROM_ONE_CLIP];
  
  for (dlong e = 0; e < Nel; ++e) {
    Point3D current_poly_verts[HEXNVERTS];
    for (int i = 0; i < HEXNVERTS; ++i) {
      current_poly_verts[i].x = EX[e*HEXNVERTS + i];
      current_poly_verts[i].y = EY[e*HEXNVERTS + i];
      current_poly_verts[i].z = EZ[e*HEXNVERTS + i];
    }
    AABB element_aabb = create_aabb_polyhedron(current_poly_verts, HEXNVERTS);
        
    std::vector<Triangle3D> element_clipped_triangles_collector;
    std::set<dlong> candidate_tri_indices; // Use std::set for unique indices
    surface_grid.get_candidate_triangles(element_aabb, candidate_tri_indices);

    for (dlong s_idx : candidate_tri_indices) { // Iterate over unique candidates
      // Optional: Precise AABB check if grid cells are coarse or for extra culling
      if (!aabbs_intersect(element_aabb, surface_grid.triangle_aabbs_cache[s_idx])) {
	continue;
      }

      Point3D current_surface_tri_verts[TRINVERTS];
      current_surface_tri_verts[0] = (Point3D){ sEX[s_idx*TRINVERTS+0], sEY[s_idx*TRINVERTS+0], sEZ[s_idx*TRINVERTS+0] };
      current_surface_tri_verts[1] = (Point3D){ sEX[s_idx*TRINVERTS+1], sEY[s_idx*TRINVERTS+1], sEZ[s_idx*TRINVERTS+1] };
      current_surface_tri_verts[2] = (Point3D){ sEX[s_idx*TRINVERTS+2], sEY[s_idx*TRINVERTS+2], sEZ[s_idx*TRINVERTS+2] };
            
      int num_newly_clipped_tris = clip_triangle_to_hexahedron(
							       current_surface_tri_verts, current_poly_verts, 
							       clipped_tris_buffer, MAX_TRIANGLES_FROM_ONE_CLIP);
      for (int t = 0; t < num_newly_clipped_tris; ++t) {
	element_clipped_triangles_collector.push_back(clipped_tris_buffer[t]);
      }
    }
    // ... (rest of the function to populate fEX, fEY, fEZ remains the same)
    dlong total_tris_for_element = element_clipped_triangles_collector.size();
    if (total_tris_for_element > 0) {
      fEX[e].resize(total_tris_for_element * TRINVERTS);
      fEY[e].resize(total_tris_for_element * TRINVERTS);
      fEZ[e].resize(total_tris_for_element * TRINVERTS);
      dlong output_coord_idx = 0;
      for (dlong t_idx = 0; t_idx < total_tris_for_element; ++t_idx) {
	for (int v = 0; v < TRINVERTS; ++v) {
	  fEX[e][output_coord_idx] = element_clipped_triangles_collector[t_idx].v[v].x;
	  fEY[e][output_coord_idx] = element_clipped_triangles_collector[t_idx].v[v].y;
	  fEZ[e][output_coord_idx] = element_clipped_triangles_collector[t_idx].v[v].z;
	  output_coord_idx++;
	}
      }
      // printf("Element %zu (Hex): %zu clipped triangles generated from %zu candidates.\n", e, total_tris_for_element, candidate_tri_indices.size());
    }
  }
}

// --- New Tetrahedron Intersection Function ---
void computeIntersectionsTet3D(
			       const memory<dfloat> &EX, const memory<dfloat> &EY, const memory<dfloat> &EZ,
			       const memory<dfloat> &sEX, const memory<dfloat> &sEY, const memory<dfloat> &sEZ,
			       std::vector<std::vector<dfloat>> &fEX, std::vector<std::vector<dfloat>> &fEY,
			       std::vector<std::vector<dfloat>> &fEZ, dlong Nel, dlong Nsurf){

  dfloat xmin = sEX[0], ymin = sEY[0], zmin = sEZ[0];
  dfloat xmax = sEX[0], ymax = sEY[0], zmax = sEZ[0];
  for (dlong e = 0; e < Nsurf; ++e) {
    for (int i = 0; i < TRINVERTS; ++i) {
      xmin = std::min(xmin, sEX[e*TRINVERTS+i]);
      xmax = std::max(xmax, sEX[e*TRINVERTS+i]);
      ymin = std::min(ymin, sEY[e*TRINVERTS+i]);
      ymax = std::max(ymax, sEY[e*TRINVERTS+i]);
      zmin = std::min(zmin, sEZ[e*TRINVERTS+i]);
      zmax = std::max(zmax, sEZ[e*TRINVERTS+i]);
    }
  }

  SpatialGrid surface_grid;
  Point3D domain_min, domain_max;
  
  domain_min = {xmin, ymin, zmin};
  domain_max = {xmax, ymax, zmax};
  surface_grid.init(domain_min, domain_max, 32);
  surface_grid.cache_triangle_aabbs(sEX, sEY, sEZ, Nsurf);
  for (dlong s = 0; s < Nsurf; ++s) surface_grid.insert_triangle(s);


  fEX.assign(Nel, {}); fEY.assign(Nel, {}); fEZ.assign(Nel, {});
  Triangle3D clipped_tris_buffer[MAX_TRIANGLES_FROM_ONE_CLIP];

  for (dlong e = 0; e < Nel; ++e) {
    Point3D current_poly_verts[TETNVERTS];
    for (int i = 0; i < TETNVERTS; ++i) {
      current_poly_verts[i].x = EX[e*TETNVERTS + i];
      current_poly_verts[i].y = EY[e*TETNVERTS + i];
      current_poly_verts[i].z = EZ[e*TETNVERTS + i];
    }
    AABB element_aabb = create_aabb_polyhedron(current_poly_verts, TETNVERTS);

    std::vector<Triangle3D> element_clipped_triangles_collector;
    std::set<dlong> candidate_tri_indices; // Use std::set for unique indices
    surface_grid.get_candidate_triangles(element_aabb, candidate_tri_indices);

    for (dlong s_idx : candidate_tri_indices) { // Iterate over unique candidates
      // Optional: Precise AABB check
      if (!aabbs_intersect(element_aabb, surface_grid.triangle_aabbs_cache[s_idx])) {
	continue;
      }

      Point3D current_surface_tri_verts[TRINVERTS];
      current_surface_tri_verts[0] = (Point3D){ sEX[s_idx*TRINVERTS+0], sEY[s_idx*TRINVERTS+0], sEZ[s_idx*TRINVERTS+0] };
      current_surface_tri_verts[1] = (Point3D){ sEX[s_idx*TRINVERTS+1], sEY[s_idx*TRINVERTS+1], sEZ[s_idx*TRINVERTS+1] };
      current_surface_tri_verts[2] = (Point3D){ sEX[s_idx*TRINVERTS+2], sEY[s_idx*TRINVERTS+2], sEZ[s_idx*TRINVERTS+2] };
            
      int num_newly_clipped_tris = clip_triangle_to_tetrahedron(
								current_surface_tri_verts, current_poly_verts,
								clipped_tris_buffer, MAX_TRIANGLES_FROM_ONE_CLIP);
      for (int t = 0; t < num_newly_clipped_tris; ++t) {
	element_clipped_triangles_collector.push_back(clipped_tris_buffer[t]);
      }
    }
    // ... (rest of the function to populate fEX, fEY, fEZ remains the same)
    dlong total_tris_for_element = element_clipped_triangles_collector.size();
    if (total_tris_for_element > 0) {
      fEX[e].resize(total_tris_for_element * TRINVERTS);
      fEY[e].resize(total_tris_for_element * TRINVERTS);
      fEZ[e].resize(total_tris_for_element * TRINVERTS);
      dlong output_coord_idx = 0;
      for (dlong t_idx = 0; t_idx < total_tris_for_element; ++t_idx) {
	for (int v = 0; v < TRINVERTS; ++v) {
	  fEX[e][output_coord_idx] = element_clipped_triangles_collector[t_idx].v[v].x;
	  fEY[e][output_coord_idx] = element_clipped_triangles_collector[t_idx].v[v].y;
	  fEZ[e][output_coord_idx] = element_clipped_triangles_collector[t_idx].v[v].z;
	  output_coord_idx++;
	}
      }
      // printf("Element %zu (Tet): %zu clipped triangles generated from %zu candidates.\n", e, total_tris_for_element, candidate_tri_indices.size());
    }
  }
}


int map_cartesian_to_biunit_tetra(
    int Nc,
    memory<dfloat> &xc,
    memory<dfloat> &yc,
    memory<dfloat> &zc, 
    memory<dfloat> &ex,
    memory<dfloat> &ey,
    memory<dfloat> &ez,
    memory<dfloat> &rc,
    memory<dfloat> &sc,
    memory<dfloat> &tc
) {
    // Extract vertex coordinates for convenience
    dfloat v0x = ex[0], v0y = ey[0], v0z = ez[0];
    dfloat v1x = ex[1], v1y = ey[1], v1z = ez[1];
    dfloat v2x = ex[2], v2y = ey[2], v2z = ez[2];
    dfloat v3x = ex[3], v3y = ey[3], v3z = ez[3];

    // Calculate components of matrix M (columns are v1-v0, v2-v0, v3-v0)
    // M = | m00  m01  m02 |
    //     | m10  m11  m12 |
    //     | m20  m21  m22 |
    dfloat m00 = v1x - v0x; dfloat m01 = v2x - v0x; dfloat m02 = v3x - v0x;
    dfloat m10 = v1y - v0y; dfloat m11 = v2y - v0y; dfloat m12 = v3y - v0y;
    dfloat m20 = v1z - v0z; dfloat m21 = v2z - v0z; dfloat m22 = v3z - v0z;

    // Calculate determinant of M
    dfloat detM = m00 * (m11 * m22 - m12 * m21) -
                  m01 * (m10 * m22 - m12 * m20) +
                  m02 * (m10 * m21 - m11 * m20);

    // Check for degenerate tetrahedron (detM is close to zero)
    // A small epsilon is used for robust floating-point comparison.
    if (fabs(detM) < 1e-12) {
#ifndef NDEBUG // Print error message only in debug builds
        fprintf(stderr, "Error: Degenerate tetrahedron, determinant is near zero (%e).\n", detM);
#endif
        // Fill output arrays with NAN or a specific error value if desired
        for (int i = 0; i < Nc; ++i) {
#ifdef NAN
            rc[i] = NAN; sc[i] = NAN; tc[i] = NAN;
#else
            // Fallback if NAN is not defined (e.g. very large number)
            rc[i] = HUGE_VAL; sc[i] = HUGE_VAL; tc[i] = HUGE_VAL;
#endif
        }
        return -1; // Indicate failure
    }

    // Calculate inverse of M: M_inv = adj(M)^T / detM
    // adj(M)^T_ij = Cofactor_ji(M)
    // M_inv[row_idx][col_idx]
    dfloat invM00 = (m11 * m22 - m12 * m21) / detM;
    dfloat invM01 = (m02 * m21 - m01 * m22) / detM; // C10 term of M / detM (transposed C01)
    dfloat invM02 = (m01 * m12 - m02 * m11) / detM; // C20 term of M / detM (transposed C02)

    dfloat invM10 = (m12 * m20 - m10 * m22) / detM; // C01 term of M / detM (transposed C10)
    dfloat invM11 = (m00 * m22 - m02 * m20) / detM; // C11 term of M / detM
    dfloat invM12 = (m02 * m10 - m00 * m12) / detM; // C21 term of M / detM (transposed C12)

    dfloat invM20 = (m10 * m21 - m11 * m20) / detM; // C02 term of M / detM (transposed C20)
    dfloat invM21 = (m01 * m20 - m00 * m21) / detM; // C12 term of M / detM (transposed C21)
    dfloat invM22 = (m00 * m11 - m01 * m10) / detM; // C22 term of M / detM

    // Loop through each point
    for (int i = 0; i < Nc; ++i) {
        dfloat Px = xc[i];
        dfloat Py = yc[i];
        dfloat Pz = zc[i];

        // Calculate RHS vector b_vec for the current point P
        // b_vec = 2*P + v0 - v1 - v2 - v3
        dfloat b_vec_x = 2.0 * Px + v0x - v1x - v2x - v3x;
        dfloat b_vec_y = 2.0 * Py + v0y - v1y - v2y - v3y;
        dfloat b_vec_z = 2.0 * Pz + v0z - v1z - v2z - v3z;

        // Calculate r, s, t for the current point: [r,s,t]^T = M_inv * b_vec
        rc[i] = invM00 * b_vec_x + invM01 * b_vec_y + invM02 * b_vec_z;
        sc[i] = invM10 * b_vec_x + invM11 * b_vec_y + invM12 * b_vec_z;
        tc[i] = invM20 * b_vec_x + invM21 * b_vec_y + invM22 * b_vec_z;
    }

    return 0; // Indicate success
}


dfloat areaTri3D(memory<dfloat> &EX, memory<dfloat> &EY, memory<dfloat> &EZ){

  dfloat x1 = EX[1]-EX[0];
  dfloat y1 = EY[1]-EY[0];
  dfloat z1 = EZ[1]-EZ[0];
  dfloat x2 = EX[2]-EX[0];
  dfloat y2 = EY[2]-EY[0];
  dfloat z2 = EZ[2]-EZ[0];

  dfloat cx = y1*z2-z1*y2;
  dfloat cy = z1*x2-x1*z2;
  dfloat cz = x1*y2-y1*x2;

  dfloat A = 0.5*sqrt(cx*cx+cy*cy+cz*cz);

  return A;

}

void elliptic_t::BuildImmersedBoundaryMatrixTet3D(mesh_t &vmesh){
  
  // are we using an immersed boundary ?
  if(settings.compareSetting("IMMERSED BOUNDARY", "FALSE")){
    ibNelements = 0;
    return;
  }
  
  // surface mesh settings  
  meshSettings_t ibmeshSettings = vmesh.settings;
  
  std::string surfMeshFile = settings.getSetting("IMMERSED BOUNDARY MESH FILE");
  
  ibmeshSettings.changeSetting("MESH FILE",  surfMeshFile.c_str());
  ibmeshSettings.changeSetting("ELEMENT TYPE", "3"); // force to use triangles 
  ibmeshSettings.report();
  
  // surface mesh
  mesh_t ibmesh(platform, ibmeshSettings, comm);
  
  std::cout << "ibMesh Nelements: " << ibmesh.Nelements << std::endl;
  std::cout << "  mesh Nelements: " << vmesh.Nelements << std::endl;
  
  // build penalty matrix kernel
  std::string oklFilePrefix = DELLIPTIC "/okl/";
  std::string oklFileSuffix = ".okl";
  std::string suffix = vmesh.elementSuffix();
  std::string fileName, kernelName;

  properties_t kernelInfo = vmesh.props; //copy base occa properties
  fileName   = oklFilePrefix + "ellipticImmersedBoundaryPenalty" + suffix + oklFileSuffix;
  kernelName = "ellipticImmersedBoundaryPenalty" + suffix;

  immersedBoundaryPenaltyKernel = platform.buildKernel(fileName, kernelName, kernelInfo);

  kernelInfo["defines/dfloat"] = pfloatString;

  floatImmersedBoundaryPenaltyKernel = platform.buildKernel(fileName, kernelName, kernelInfo);

  
  std::vector<std::vector<dfloat>> fEX;
  std::vector<std::vector<dfloat>> fEY;
  std::vector<std::vector<dfloat>> fEZ;
  
  computeIntersectionsTet3D(vmesh.EX, vmesh.EY, vmesh.EZ,
			    ibmesh.EX, ibmesh.EY, ibmesh.EZ,
			    fEX, fEY, fEZ,
			    vmesh.Nelements, ibmesh.Nelements);

  ibNelements = 0;
  for(dlong e=0;e<vmesh.Nelements;++e){
    dlong Ntri = fEX[e].size()/TRINVERTS;
    if(Ntri>0){
      ++ibNelements;
    }
  }

  // build list of ib elements
  memory<dlong> ibElements(ibNelements);  
  
  dlong ib = 0;
  for(dlong e=0;e<vmesh.Nelements;++e){
    dlong Ntri = fEX[e].size()/TRINVERTS;
    if(Ntri>0){
      //      printf("ib: %d Element:  %d Ntri: %d\n", ib, e, Ntri);
      ibElements[ib] = e;
      ++ib;
    }
  }
  
  
  // need to check size later

  memory<dfloat> ibCubr, ibCubs, ibCubt, ibCubw;
  int ibCubN = vmesh.N*2;
  int ibCubNp; 
  vmesh.CubatureNodesTri2D(ibCubN, ibCubNp, ibCubr, ibCubs, ibCubw);

  // zero for accumulation
  memory<dfloat> ibMM(ibNelements*vmesh.Np*vmesh.Np, (dfloat)0.);
  memory<dfloat> ibInvV;

  vmesh.VandermondeTet3D(vmesh.N, vmesh.r, vmesh.s, vmesh.t, ibInvV);
  linAlg_t::matrixInverse(vmesh.Np, ibInvV);

  // find maximum reciprocal face orthogonal element length
  // for all elements in immersed boundary patch
  dfloat maxInvH = 0;
  for(ib=0;ib<ibNelements;++ib){
    dlong e = ibElements[ib];

    for(int f=0;f<vmesh.Nfaces;++f){
      dlong id = e*vmesh.Nsgeo*vmesh.Nfaces + f*vmesh.Nsgeo + vmesh.IHID;
      maxInvH = std::max(maxInvH, vmesh.sgeo[id]);
    }
  }

  // take global max among ranks
  vmesh.comm.Allreduce(maxInvH, comm_t::Max);
  
  // form penalty
  //  dfloat maxTau = vmesh.N*vmesh.N*maxInvH;
  dfloat maxTau = pow(vmesh.N, 3)*pow(maxInvH,2);
 
  std::cout << "maxTau: " << maxTau << std::endl;

  memory<dlong> logAreaCounts(100,0);
  
  // slow to get started
#if !defined(LIBP_DEBUG)
#pragma omp parallel for
#endif
  for(ib=0;ib<ibNelements;++ib){
    
    memory<dfloat> ibCubV(ibCubNp*vmesh.Np);
    memory<dfloat> ibCubInterp(ibCubNp*vmesh.Np);
    
    memory<dfloat> ibEX(TRINVERTS), ibEY(TRINVERTS), ibEZ(TRINVERTS);
    memory<dfloat> ibEXTet(TETNVERTS), ibEYTet(TETNVERTS), ibEZTet(TETNVERTS);
    memory<dfloat> ibCubrTet(ibCubNp), ibCubsTet(ibCubNp), ibCubtTet(ibCubNp);
    memory<dfloat> ibCubx(ibCubNp), ibCuby(ibCubNp), ibCubz(ibCubNp);
    
    if((ib%1000)==0)
      printf("building element %d of %d\n", ib, ibNelements);
    
    dlong e = ibElements[ib];
    
    // for each sub-triangle
    for(int tri=0;tri<fEX[e].size()/TRINVERTS;++tri){

      // grab vertex coordinates
      for(int v=0;v<TRINVERTS;++v){
	ibEX[v] = fEX[e][tri*TRINVERTS+v];
	ibEY[v] = fEY[e][tri*TRINVERTS+v];
	ibEZ[v] = fEZ[e][tri*TRINVERTS+v];
      }

      // grab tet vertex coordinates
      for(int v=0;v<TETNVERTS;++v){
	ibEXTet[v] = vmesh.EX[e*TETNVERTS+v];
	ibEYTet[v] = vmesh.EY[e*TETNVERTS+v];
	ibEZTet[v] = vmesh.EZ[e*TETNVERTS+v];
      }
      
      // lay down tri cubature nodes on this triangle
      for(int n=0;n<ibCubNp;++n){
	ibCubx[n] = -0.5*(ibCubr[n]+ibCubs[n])*ibEX[0];
	ibCuby[n] = -0.5*(ibCubr[n]+ibCubs[n])*ibEY[0];
	ibCubz[n] = -0.5*(ibCubr[n]+ibCubs[n])*ibEZ[0];
	ibCubx[n] += 0.5*(1+ibCubr[n])*ibEX[1];
	ibCuby[n] += 0.5*(1+ibCubr[n])*ibEY[1];
	ibCubz[n] += 0.5*(1+ibCubr[n])*ibEZ[1];
	ibCubx[n] += 0.5*(1+ibCubs[n])*ibEX[2];
	ibCuby[n] += 0.5*(1+ibCubs[n])*ibEY[2];
	ibCubz[n] += 0.5*(1+ibCubs[n])*ibEZ[2];
      }

      // map tri cubature nodes to local coordinates
      map_cartesian_to_biunit_tetra(ibCubNp, ibCubx, ibCuby, ibCubz, 
				    ibEXTet, ibEYTet,ibEZTet, 
				    ibCubrTet, ibCubsTet, ibCubtTet);
      
      // evaluate PKDO at tet nodes
      vmesh.VandermondeTet3D(vmesh.N, ibCubrTet, ibCubsTet, ibCubtTet, ibCubV);

      // construction interpolation operator (W&B to IB fragment cubature nodes)
      for(int n=0;n<ibCubNp;++n){
	for(int m=0;m<vmesh.Np;++m){
	  dfloat tmp = 0;
	  for(int i=0;i<vmesh.Np;++i){
	    tmp += ibCubV[n*vmesh.Np+i]*ibInvV[i*vmesh.Np+m];
	  }
	  ibCubInterp[n*vmesh.Np+m] = tmp;
	}
      }

      // compute area of triangle (/2)
      dfloat J = fabs(areaTri3D(ibEX, ibEY, ibEZ)/2.); // 0.5*|edge 0 x edge 2| divided by area of reference triangle

      dlong Jlog10 = log10(J);
      Jlog10 = std::max(-15,Jlog10);
      Jlog10 = std::min( 15,Jlog10);

#pragma omp atomic
      ++logAreaCounts[Jlog10+15];
      
      //      if(sqrt(J)<1e-5)
      //	printf("sqrt(J)=%g\n", sqrt(J));
      
      for(int m=0;m<vmesh.Np;++m){
	for(int n=0;n<vmesh.Np;++n){

	  dfloat tmp = 0;
	  for(int i=0;i<ibCubNp;++i){
	    tmp += ibCubInterp[i*vmesh.Np+m]*ibCubInterp[i*vmesh.Np+n]*ibCubw[i];
	  }
	  tmp *= J*maxTau;

	  // these are symmetric, so order doesn't matter. Should just store symmetric part
	  ibMM[ib*vmesh.Np*vmesh.Np + m*vmesh.Np + n] += tmp;
	}
      }
    }
  }

#pragma omp barrier

#if 0  
  printf("MM: \n");
  for(int n=0;n<vmesh.Np;++n){
    for(int m=0;m<vmesh.Np;++m){
      printf("%17.15le ", ibMM[n*vmesh.Np+m]);
    }
    printf("\n");
  }

  for(int p=0;p<30;++p){
    printf("10^{%d} count: %d\n", p-15, logAreaCounts[p]);
  }
#endif
  memory<float>  floatIbMM(ibNelements*vmesh.Np*vmesh.Np, (float)0.);
  for(dlong n=0;n<mesh.Np*mesh.Np*ibNelements;++n){
    floatIbMM[n] = ibMM[n];
  }
  
  o_ibMM = platform.malloc<dfloat>(ibMM);
  o_floatIbMM = platform.malloc<float>(floatIbMM);
  o_ibElements = platform.malloc<dlong>(ibElements);

  // TW: need to scatter diagonal of matrices into full vector and gather with ogs into full diagonal
  memory<dfloat> ibDiagAL(vmesh.Nelements*vmesh.Np,(dfloat)0.);
  for(ib=0;ib<ibNelements;++ib){
    dlong e = ibElements[ib];
    for(int n=0;n<vmesh.Np;++n){
      dlong idMM = ib*vmesh.Np*vmesh.Np + n*vmesh.Np + n;
      dlong idDiagMM = e*vmesh.Np + n;
      ibDiagAL[idDiagMM] += ibMM[idMM];
    }
  }

  //gather the diagonal to assemble it
  ibDiagA.malloc(Ndofs);
  ogsMasked.Gather(ibDiagA, ibDiagAL, 1, ogs::Add, ogs::Trans);
  floatIbDiagA.malloc(Ndofs);
  for(dlong n=0;n<Ndofs;++n){
    floatIbDiagA[n] = ibDiagA[n];
  }

  
}
  
// Modified VTU writer and computeIntersectionsBruteForce
void writeFragmentsVTU(const std::string& filename,
                       const std::vector<std::vector<dfloat>>& fEX, // All X-coords for tris in element e
                       const std::vector<std::vector<dfloat>>& fEY, // All Y-coords for tris in element e
                       const std::vector<std::vector<dfloat>>& fEZ) { // All Z-coords for tris in element e

  std::ofstream out(filename);
  if (!out.is_open()) {
    fprintf(stderr, "Error: Could not open VTU file %s for writing.\n", filename.c_str());
    return;
  }

  out << "<?xml version=\"1.0\"?>\n";
  out << "<VTKFile type=\"UnstructuredGrid\" version=\"0.1\" byte_order=\"LittleEndian\" compressor=\"vtkZLibDataCompressor\">\n"; // Added compressor
  out << "  <UnstructuredGrid>\n";

  int totalGlobalPoints = 0;
  int totalGlobalTriangles = 0;

  for (dlong e = 0; e < fEX.size(); ++e) {
    // fEX[e].size() is the number of *vertices* for element e's fragments,
    // which should be num_tris_in_e * TRINVERTS
    if (fEX[e].size() > 0 && (fEX[e].size() % TRINVERTS == 0)) {
      totalGlobalPoints += fEX[e].size();
      totalGlobalTriangles += fEX[e].size() / TRINVERTS;
    }
  }

  //   printf("Writing VTU: totalGlobalPoints = %d, totalGlobalTriangles = %d\n", totalGlobalPoints, totalGlobalTriangles);
  
  out << "    <Piece NumberOfPoints=\"" << totalGlobalPoints << "\" NumberOfCells=\"" << totalGlobalTriangles << "\">\n";

  // --- Points Data ---
  out << "      <Points>\n";
  out << "        <DataArray type=\"Float64\" Name=\"Coordinates\" NumberOfComponents=\"3\" format=\"ascii\">\n";
  for (dlong e = 0; e < fEX.size(); ++e) {
    // fEX[e].size() is the number of vertices for this element's fragments
    for (dlong i = 0; i < fEX[e].size(); ++i) { 
      out << fEX[e][i] << " " << fEY[e][i] << " " << fEZ[e][i] << "\n";
    }
  }
  out << "        </DataArray>\n";
  out << "      </Points>\n";

  // --- Cells Data (Connectivity, Offsets, Types for Triangles) ---
  if (totalGlobalTriangles > 0) {
    out << "      <Cells>\n";
    
    // Connectivity: global point indices for each triangle
    out << "        <DataArray type=\"Int64\" Name=\"connectivity\" format=\"ascii\">\n"; // Use Int64 for large meshes
    int current_global_point_idx = 0;
    for (dlong e = 0; e < fEX.size(); ++e) {
      if (fEX[e].size() > 0 && (fEX[e].size() % TRINVERTS == 0)) {
	int num_tris_in_e = fEX[e].size() / TRINVERTS;
	for (int t = 0; t < num_tris_in_e; ++t) {
	  out << current_global_point_idx     << " "  // Vertex 0 of current triangle
	      << current_global_point_idx + 1 << " "  // Vertex 1
	      << current_global_point_idx + 2 << "\n"; // Vertex 2
	  current_global_point_idx += TRINVERTS;
	}
      }
    }
    out << "        </DataArray>\n";

    // Offsets: end position of each cell's connectivity list
    out << "        <DataArray type=\"Int64\" Name=\"offsets\" format=\"ascii\">\n"; // Use Int64
    long long current_offset_val = 0; // Use long long for large offsets
    for (dlong e = 0; e < fEX.size(); ++e) {
      if (fEX[e].size() > 0 && (fEX[e].size() % TRINVERTS == 0)) {
	int num_tris_in_e = fEX[e].size() / TRINVERTS;
	for (int t = 0; t < num_tris_in_e; ++t) {
	  current_offset_val += TRINVERTS; // Each triangle cell has 3 points
	  out << current_offset_val << "\n";
	}
      }
    }
    out << "        </DataArray>\n";

    // Types: VTK_TRIANGLE = 5
    out << "        <DataArray type=\"UInt8\" Name=\"types\" format=\"ascii\">\n"; // UInt8 is standard
    for (dlong e = 0; e < fEX.size(); ++e) {
      if (fEX[e].size() > 0 && (fEX[e].size() % TRINVERTS == 0)) {
	int num_tris_in_e = fEX[e].size() / TRINVERTS;
	for (int t = 0; t < num_tris_in_e; ++t) {
	  out << "5\n"; // VTK_TRIANGLE
	}
      }
    }
    out << "        </DataArray>\n";
    out << "      </Cells>\n";

    // --- CellData for ElementID ---
    out << "      <CellData Scalars=\"ElementID\">\n"; // Field data associated with cells (triangles)
    out << "        <DataArray type=\"Int32\" Name=\"ElementID\" format=\"ascii\">\n";
    for (dlong e = 0; e < fEX.size(); ++e) {
      if (fEX[e].size() > 0 && (fEX[e].size() % TRINVERTS == 0)) {
	int num_tris_in_e = fEX[e].size() / TRINVERTS;
	for (int t = 0; t < num_tris_in_e; ++t) {
	  out << e << "\n"; // Output the original hex element index for each triangle
	}
      }
    }
    out << "        </DataArray>\n";
    out << "      </CellData>\n";
  } else { // Handle case with no cells
    out << "      <Cells>\n";
    out << "        <DataArray type=\"Int64\" Name=\"connectivity\" format=\"ascii\">\n";
    out << "        </DataArray>\n";
    out << "        <DataArray type=\"Int64\" Name=\"offsets\" format=\"ascii\">\n";
    out << "        </DataArray>\n";
    out << "        <DataArray type=\"UInt8\" Name=\"types\" format=\"ascii\">\n";
    out << "        </DataArray>\n";
    out << "      </Cells>\n";
    out << "      <CellData Scalars=\"ElementID\">\n";
    out << "        <DataArray type=\"Int32\" Name=\"ElementID\" format=\"ascii\">\n";
    out << "        </DataArray>\n";
    out << "      </CellData>\n";
  }

  out << "    </Piece>\n";
  out << "  </UnstructuredGrid>\n";
  out << "</VTKFile>\n";
  out.close();
}

// Output all original surface triangles to verify what was supposed to be clipped
void writeOriginalSurfaceVTU(const dlong Nelements,
			     const memory<dfloat> &sEX,
			     const memory<dfloat> &sEY,
			     const memory<dfloat> &sEZ,
                             const std::string& filename) {
  std::ofstream out(filename);
  out << "<?xml version=\"1.0\"?>\n";
  out << "<VTKFile type=\"UnstructuredGrid\" version=\"0.1\" byte_order=\"LittleEndian\">\n";
  out << "  <UnstructuredGrid>\n";
  out << "    <Piece NumberOfPoints=\"" << sEX.size() << "\" NumberOfCells=\"" << sEX.size() / 3 << "\">\n";
  out << "      <Points>\n";
  out << "        <DataArray type=\"Float64\" NumberOfComponents=\"3\" format=\"ascii\">\n";
  for (dlong i = 0; i < Nelements*3; ++i)
    out << sEX[i] << " " << sEY[i] << " " << sEZ[i] << "\n";
  out << "        </DataArray>\n";
  out << "      </Points>\n";

  out << "      <Cells>\n";
  out << "        <DataArray type=\"Int32\" Name=\"connectivity\" format=\"ascii\">\n";
  for (dlong i = 0; i < Nelements*3; i += 3)
    out << i << " " << i + 1 << " " << i + 2 << "\n";
  out << "        </DataArray>\n";

  out << "        <DataArray type=\"Int32\" Name=\"offsets\" format=\"ascii\">\n";
  for (dlong i = 3; i <= Nelements*3; i += 3)
    out << i << "\n";
  out << "        </DataArray>\n";

  out << "        <DataArray type=\"UInt8\" Name=\"types\" format=\"ascii\">\n";
  for (dlong i = 0; i < Nelements*3; i += 3)
    out << "5\n"; // VTK_TRIANGLE
  out << "        </DataArray>\n";
  out << "      </Cells>\n";
  out << "    </Piece>\n";
  out << "  </UnstructuredGrid>\n";
  out << "</VTKFile>\n";
}

